"""Core domain models for inference requests and responses."""

import time
import uuid
from typing import Any

from pydantic import BaseModel, ConfigDict, Field, field_validator


class InferenceRequest(BaseModel):
    """Domain model representing a single model inference request.

    This model is backend-agnostic and fully independent of any HTTP framework
    or specific engine runtime (e.g. vLLM, MLX).
    """

    model_config = ConfigDict(frozen=True, extra="forbid")

    request_id: str = Field(
        default_factory=lambda: uuid.uuid4().hex,
        description="Unique identifier for tracking the request through the serving pipeline.",
    )
    model: str = Field(
        ...,
        min_length=1,
        description="Identifier of the target model to execute inference against.",
    )
    prompt: str = Field(
        ...,
        min_length=1,
        description="Input text prompt for text generation.",
    )
    max_tokens: int = Field(
        default=128,
        gt=0,
        description="Maximum number of tokens to generate.",
    )
    temperature: float = Field(
        default=0.7,
        ge=0.0,
        le=2.0,
        description="Sampling temperature between 0.0 (deterministic) and 2.0.",
    )
    priority: int = Field(
        default=0,
        description="Scheduling priority level (higher numbers denote higher priority).",
    )
    metadata: dict[str, Any] = Field(
        default_factory=dict,
        description="Arbitrary user or system metadata (e.g., tenant ID, trace headers).",
    )

    @field_validator("prompt")
    @classmethod
    def validate_prompt_not_empty(cls, v: str) -> str:
        """Ensure the prompt is not composed purely of whitespace."""
        if not v.strip():
            raise ValueError("Prompt cannot be empty or whitespace-only.")
        return v


class InferenceResponse(BaseModel):
    """Domain model representing the result of an inference execution."""

    model_config = ConfigDict(frozen=True, extra="forbid")

    request_id: str = Field(
        ...,
        description="Identifier corresponding to the originating InferenceRequest.",
    )
    generated_text: str = Field(
        ...,
        description="The text generated by the inference backend.",
    )
    input_tokens: int = Field(
        ...,
        ge=0,
        description="Count of tokens in the input prompt.",
    )
    output_tokens: int = Field(
        ...,
        ge=0,
        description="Count of tokens generated in the response.",
    )
    latency_ms: float = Field(
        ...,
        ge=0.0,
        description="Execution latency measured in milliseconds.",
    )
    backend_name: str = Field(
        ...,
        min_length=1,
        description="Name of the backend engine that processed the request.",
    )
    finish_reason: str = Field(
        default="stop",
        description="Reason generation terminated (e.g. 'stop', 'length').",
    )
    metadata: dict[str, Any] = Field(
        default_factory=dict,
        description="Backend-specific or pipeline execution metadata.",
    )


class InferenceBatch(BaseModel):
    """Domain model representing an immutable grouped batch of inference requests."""

    model_config = ConfigDict(frozen=True, extra="forbid")

    batch_id: str = Field(
        default_factory=lambda: uuid.uuid4().hex,
        description="Unique identifier for tracking the formed batch.",
    )
    requests: tuple[InferenceRequest, ...] = Field(
        ...,
        description="Ordered sequence of inference requests forming this batch.",
    )
    created_at: float = Field(
        default_factory=time.perf_counter,
        description="Monotonic creation timestamp measured via time.perf_counter().",
    )

    @field_validator("requests")
    @classmethod
    def validate_requests_not_empty(
        cls, v: tuple[InferenceRequest, ...]
    ) -> tuple[InferenceRequest, ...]:
        """Ensure batch contains at least one inference request."""
        if not v:
            raise ValueError("InferenceBatch cannot be empty; must contain at least one request.")
        return v

    @property
    def size(self) -> int:
        """Number of individual inference requests in the batch."""
        return len(self.requests)

    @property
    def request_ids(self) -> list[str]:
        """Ordered list of request identifiers in the batch."""
        return [r.request_id for r in self.requests]

    @property
    def total_max_tokens(self) -> int:
        """Sum of max_tokens limits across all requests in the batch."""
        return sum(r.max_tokens for r in self.requests)
