"""Core domain models for inference requests and responses."""

import uuid
from typing import Any

from pydantic import BaseModel, ConfigDict, Field, field_validator


class InferenceRequest(BaseModel):
    """Domain model representing a single model inference request.

    This model is backend-agnostic and fully independent of any HTTP framework
    or specific engine runtime (e.g. vLLM, MLX).
    """

    model_config = ConfigDict(frozen=True, extra="forbid")

    request_id: str = Field(
        default_factory=lambda: uuid.uuid4().hex,
        description="Unique identifier for tracking the request through the serving pipeline.",
    )
    model: str = Field(
        ...,
        min_length=1,
        description="Identifier of the target model to execute inference against.",
    )
    prompt: str = Field(
        ...,
        min_length=1,
        description="Input text prompt for text generation.",
    )
    max_tokens: int = Field(
        default=128,
        gt=0,
        description="Maximum number of tokens to generate.",
    )
    temperature: float = Field(
        default=0.7,
        ge=0.0,
        le=2.0,
        description="Sampling temperature between 0.0 (deterministic) and 2.0.",
    )
    priority: int = Field(
        default=0,
        description="Scheduling priority level (higher numbers denote higher priority).",
    )
    metadata: dict[str, Any] = Field(
        default_factory=dict,
        description="Arbitrary user or system metadata (e.g., tenant ID, trace headers).",
    )

    @field_validator("prompt")
    @classmethod
    def validate_prompt_not_empty(cls, v: str) -> str:
        """Ensure the prompt is not composed purely of whitespace."""
        if not v.strip():
            raise ValueError("Prompt cannot be empty or whitespace-only.")
        return v


class InferenceResponse(BaseModel):
    """Domain model representing the result of an inference execution."""

    model_config = ConfigDict(frozen=True, extra="forbid")

    request_id: str = Field(
        ...,
        description="Identifier corresponding to the originating InferenceRequest.",
    )
    generated_text: str = Field(
        ...,
        description="The text generated by the inference backend.",
    )
    input_tokens: int = Field(
        ...,
        ge=0,
        description="Count of tokens in the input prompt.",
    )
    output_tokens: int = Field(
        ...,
        ge=0,
        description="Count of tokens generated in the response.",
    )
    latency_ms: float = Field(
        ...,
        ge=0.0,
        description="Execution latency measured in milliseconds.",
    )
    backend_name: str = Field(
        ...,
        min_length=1,
        description="Name of the backend engine that processed the request.",
    )
    finish_reason: str = Field(
        default="stop",
        description="Reason generation terminated (e.g. 'stop', 'length').",
    )
    metadata: dict[str, Any] = Field(
        default_factory=dict,
        description="Backend-specific or pipeline execution metadata.",
    )
